name: network_proxy
description: network proxy
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+5

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  basic_utils: ^5.6.1
  logger: ^2.0.1
  date_format: ^2.0.7
  window_manager: ^0.3.6
  desktop_multi_window:
    git:
      url: https://gitee.com/wanghongenpin/flutter-plugins.git
      path: packages/desktop_multi_window
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  proxy_manager: ^0.0.3
  qr_flutter: ^4.1.0
  easy_permission: ^1.0.0
  qrscan: ^0.3.3
  flutter_barcode_scanner: ^2.0.0
  flutter_toastr: ^1.0.3
  share_plus: ^7.1.0
  brotli: ^0.6.0
  installed_apps: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/certs/ca.crt
    - assets/certs/ca_private.der
    - assets/icon.png
