name: network_proxy
description: ProxyPin
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4+14

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  crypto: ^3.0.5
  cupertino_icons: ^1.0.2
  basic_utils: ^5.7.0
  logger: ^2.4.0
  date_format: ^2.0.9
  window_manager: ^0.4.2
  desktop_multi_window:
    git:
      url: https://gitee.com/wanghongenpin/flutter-plugins.git
      path: packages/desktop_multi_window
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  proxy_manager: ^0.0.3
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  flutter_qr_reader: ^1.0.5
  flutter_toastr: ^1.0.3
  share_plus: ^10.1.0
  brotli: ^0.6.0
  flutter_js: ^0.8.1
  flutter_code_editor: ^0.3.2
  flutter_desktop_context_menu: ^0.2.0
  file_picker: ^8.1.3
  file_selector: ^1.0.3
  win32audio: ^1.3.1
  device_info_plus: ^11.1.0
  shared_preferences: ^2.3.2
  image_pickers: ^2.0.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/certs/ca.crt
    - assets/certs/ca_key.pem
    - assets/icon.png
